# Site settings
title: FabAcademy @ Fab Lab Cascina
email: fiore.basile@gmail.com
description: Resources for FabAcademy 2015 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://fabacademy.fablabcascina.org" # the base hostname & protocol for your site
twitter_username: fablabcascina
github_username:  fablabcascina
phone: "+393284576081"
# Build settings
markdown: kramdown
